@mainUrl = http://localhost:3000

### GET all transaction
GET {{mainUrl}}/transactions
Content-Type: application/json 

### POST transaction
POST {{mainUrl}}/transactions
Content-Type:application/json


{
  "date": "2024-01-15",
  "name": "Cumparaturi",
  "price": 150.50,
  "CategoryId": 1,
  "isNeed": "Need",
  "paymentMethod": "Card"
}

### PUT transaction

PUT {{mainUrl}}/transactions/2
Content-Type: application/json

{
  "name": "Cumparaturi modificate",
  "price": 200
} 

### DELETE TRANSACTION
DELETE {{mainUrl}}/transactions/2